spring.application.name=msmatricula
# Puerto del Servidor
server.port=8081

# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ms_matricula?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=matricula_service_admin
spring.datasource.password=Matriculas_2026@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect