spring.application.name=msmatricula
# Puerto del Servidor
server.port=8086

# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://bd-my-ohiggins.cdabac7ubiin.us-east-1.rds.amazonaws.com:3306/MATRICULA?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:My_ohiggins2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Carga datos iniciales luego de crear las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always