# Puerto en el que se ejecutará este microservicio
server.port=8085

# Nombre de la aplicación
spring.application.name=ms-calendarioescolar

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:calendariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONFIGURACIÓN JPA / HIBERNATE
# ===============================
# update: actualiza el esquema si hay cambios sin borrar los datos existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# ===============================
# CONFIGURACIÓN CONSOLA H2
# ===============================
# Permite acceder a http://localhost:8083/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
