spring.application.name=anotaciones

#MANJEJO DE ERRORES

#Incluye los errores de datos entrantes en las respuestas HTTP
spring.web.error.include-binding-errors=always

#Incluye el mensaje detallado del error en las respuestas HTTP
spring.web.error.include-message=always

#CONEXION A LA BASE DE DATOS

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ANOTACIONES?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=anot_service_admin
spring.datasource.password=Anot_2026@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#CONFIGURACION JPA

#Crea las tablas de las entidades y las borra al apagar
#(CAMBIAR A update CUANDO EL MS ESTE LISTO)
spring.jpa.hibernate.ddl-auto=create-drop  

#Muestra las consultas sql en los logs
spring.jpa.show-sql=true

#Para que los logs de las consultas se entiendan al leerlas
spring.jpa.properties.hibernate.format_sql=true

#Esto permite que no sea necesario escribir consultas sql manuales en el codigo. 
# y solo escribir en lenguaje java, esto transforma lo escrito en consultas sql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#CONEXIONES HIKARICP

#Tiempo máximo de espera para obtener una conexión del pool. 30000ms = 30 segundos.
spring.datasource.hikari.connection-timeout=30000

#Número máximo de conexiones simultáneas en el pool
spring.datasource.hikari.maximum-pool-size=10

# Puerto en el que se ejecutará este microservicio
server.port=8083
